services:
  - type: web
    name: bughunt-server
    env: node
    buildCommand: npm install && cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_SSL
        sync: false
      - key: PORT
        value: 5001
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: bughunt-client
    env: static
    buildCommand: npm install && cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://bughunt.onrender.com
      - key: REACT_APP_AUTH0_DOMAIN
        value: dev-6jjadkywt5r7vivx.us.auth0.com
      - key: REACT_APP_AUTH0_CLIENT_ID
        value: obHs9V2fQXchiUGXZhrjNRVGTVnOjtdS
      - key: REACT_APP_AUTH0_CALLBACK_URL
        value: https://bughuntapp.onrender.com/callback 